Repository Programmiermethoden/PM-Dungeon, pull requests merged in 2022-06, with the labels that each got.

#334 [GENERATOR] Perlin Noise #332
  code/core/src/level/generator/perlinNoise/NoiseArea.java
  code/core/src/level/generator/perlinNoise/PerlinNoise.java
  code/core/src/level/generator/perlinNoise/PerlinNoiseGenerator.java
  code/core/test/level/generator/PerlinNoiseGeneratorTest.java
Labels: enhancement, 5.x

#350 Update: github_ci.yml, cache gradle wrapper
  .github/workflows/github_ci.yml
  code/gradle.properties
Labels: bug, 5.x

#336 [GITHUB] New Issue-Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/controller.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/graphics.md
  .github/ISSUE_TEMPLATE/level.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/test.md
  .github/ISSUE_TEMPLATE/toolchain.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#353 Merge frame methods
  code/core/src/controller/MainController.java
  code/core/src/starter/DefaultMainController.java
  code/core/test/controller/MainControllerTest.java
Labels: enhancement, 5.x
