Repository Programmiermethoden/PM-Dungeon, pull requests merged in 2022-10, with the labels that each got.

#399 MyGame vereinfachen
  code/core/src/starter/MyGame.java
Labels: bug, 5.x

#391 split ILevel into three interfaces
  code/core/src/level/elements/ILevel.java
  code/core/src/level/elements/IPathable.java
  code/core/src/level/elements/ITileable.java
Labels: bug, 5.x

#402 ScreenText Konstruktor private -> public
  code/core/src/basiselements/hud/ScreenText.java
Labels: bug, 5.x

#406 Build.gradle cleanup
  code/build.gradle
Labels: enhancement, 5.x

#407 implement Textfield
  code/core/src/basiselements/hud/ScreenInput.java
  code/core/src/basiselements/hud/TextFieldStyleBuilder.java
Labels: feature, SHK
