Repository Programmiermethoden/PM-Dungeon, pull requests merged in 2022-05, with the labels that each got.

#254 better exit and start placment
  code/core/src/level/elements/Level.java
  code/core/src/level/generator/dungeong/roomg/RoomTemplate.java
  code/core/src/level/tools/LevelElement.java
  code/core/src/level/tools/TileTextureFactory.java
Labels: bug, enhancement

#255 dont copy layout in getLayout
  code/core/src/level/elements/room/Room.java
Labels: bug, enhancement

#249 konstante Laufzeit der getTileAt(coordinate) Methode in Level
  code/build.gradle
  code/core/src/level/elements/Level.java
Labels: bug

#266 Develop: konstante Laufzeit der getTileAt(coordinate) Methode in Level
  .github/workflows/github_ci.yml
  README.md
  code/build.gradle
  code/core/src/level/elements/Level.java
Labels: enhancement

#273 add pause toggle for the gameloop
  code/core/src/controller/MainController.java
  code/core/test/controller/MainControllerTest.java
Labels: enhancement

#275 Update github_ci.yml checkstyle
  .github/workflows/github_ci.yml
Labels: bug

#280 Workflow: Update used Actions
  .github/workflows/github_ci.yml
  .github/workflows/publish_github.yml
  .github/workflows/publish_maven.yml
Labels: bug, enhancement

#282 bugfix: levelgenerator only one room accessible
  code/core/src/level/elements/Level.java
  code/core/src/level/elements/room/Tile.java
Labels: bug, enhancement

#283 master-bugfix: levelgenerator only one room accessible
  code/core/src/level/elements/Level.java
  code/core/src/level/elements/room/Tile.java
Labels: bug, enhancement

#285 Levelgenerator
  code/core/src/level/elements/Level.java
  code/core/src/level/elements/room/Tile.java
  code/core/src/level/generator/dungeong/levelg/LevelG.java
Labels: enhancement

#279 Tooling: Update Gradle-Plugins and Tools
  code/build.gradle
  code/core/src/basiselements/Animatable.java
  code/core/src/basiselements/DungeonElement.java
  code/core/src/controller/MainController.java
  code/core/src/graphic/DungeonCamera.java
  code/core/src/level/elements/Level.java
  code/core/src/level/elements/astar/TileHeuristic.java
  code/core/src/level/elements/graph/Graph.java
  code/core/src/level/elements/room/Room.java
  code/core/src/level/elements/room/Tile.java
  code/core/src/level/generator/dungeong/levelg/ConfigurationSpace.java
  code/core/src/level/generator/dungeong/roomg/RoomTemplate.java
Labels: bug, enhancement

#288 Update buildscript repositories
  code/build.gradle
Labels: enhancement

#289 Update workflow SpotBugs
  .github/workflows/github_ci.yml
Labels: enhancement

#265 Layer system for master
  code/core/src/basiselements/DungeonElement.java
  code/core/src/basiselements/Entity.java
  code/core/src/basiselements/HUDElement.java
  code/core/src/controller/AbstractController.java
  code/core/src/controller/ControllerLayer.java
  code/core/src/controller/EntityController.java
  code/core/src/controller/HUDController.java
  code/core/test/controller/EntityControllerTest.java
Labels: enhancement

#291 Update build.gradle, update toolVersion (master)
  code/build.gradle
Labels: enhancement, 4.x, high prio

#293 Update workflows and buildscripts (develop)
  .github/workflows/github_ci.yml
  .github/workflows/publish_github.yml
  .github/workflows/publish_maven.yml
  code/build.gradle
  code/checkstyle-config/checks.xml
  code/core/src/basiselements/Animatable.java
  code/core/src/basiselements/DungeonElement.java
  code/core/src/controller/MainController.java
  code/core/src/graphic/DungeonCamera.java
  code/core/src/level/elements/Level.java
  code/core/src/level/elements/astar/TileHeuristic.java
  code/core/src/level/elements/graph/Graph.java
  code/core/src/level/elements/room/Room.java
  code/core/src/level/elements/room/Tile.java
  code/core/src/level/generator/dungeong/levelg/ConfigurationSpace.java
  code/core/src/level/generator/dungeong/roomg/RoomTemplate.java
Labels: 5.x

#296 Update release workflow (master)
  .github/workflows/publish_github.yml
  .github/workflows/publish_maven.yml
  code/build.gradle
Labels: enhancement, 4.x, high prio

#257 improve level ctor
  code/core/src/level/elements/Level.java
  code/core/src/level/generator/LevelLoader/LevelLoader.java
  code/core/src/level/generator/dummy/DummyGenerator.java
  code/core/src/level/generator/dungeong/levelg/LevelG.java
Labels: enhancement, 4.x

#299 Pausefunktion für Gameloop
  code/core/src/controller/MainController.java
  code/core/test/controller/MainControllerTest.java
Labels: enhancement, 5.x

#298 Door bug
  code/core/src/level/elements/Level.java
  code/core/src/level/elements/room/Tile.java
Labels: bug, 5.x

#301 Remove version number (master, 5.x)
  code/build.gradle
Labels: bug, 5.x

#303 Hotfix for AbstractController (version4)
  code/core/src/controller/AbstractController.java
  code/core/test/controller/EntityControllerTest.java
Labels: bug, 4.x, high prio

#310 Levelgenerierung: Remove Wildcards and Replacement
  code/core/src/controller/MainController.java
  code/core/src/level/generator/dungeong/levelg/LevelG.java
  code/core/src/level/generator/dungeong/roomg/Replacement.java
  code/core/src/level/generator/dungeong/roomg/ReplacementLoader.java
  code/core/src/level/generator/dungeong/roomg/RoomTemplate.java
  code/core/src/level/tools/DesignLabel.java
  code/core/src/level/tools/LevelElement.java
  code/core/src/tools/Constants.java
Labels: enhancement, 5.x

#300 Layer system 5
  code/core/src/basiselements/DungeonElement.java
  code/core/src/basiselements/Entity.java
  code/core/src/basiselements/HUDElement.java
  code/core/src/controller/AbstractController.java
  code/core/src/controller/ControllerLayer.java
  code/core/src/controller/EntityController.java
  code/core/src/controller/HUDController.java
  code/core/test/controller/EntityControllerTest.java
Labels: enhancement, 5.x

#322 rename Tile.texturePath to Tile.texture
  code/core/src/level/elements/room/Tile.java
Labels: bug, 5.x

#330 Remove Xms and Xmx options
  code/gradle.properties
Labels: 5.x

#338 [BUG] Javadoc for beginFrame/endFrame/setup
  code/core/src/controller/MainController.java
Labels: bug, documentation, 4.x

#339 [BUG] add Javadoc for beginFrame/endFrame/setup
  code/core/src/controller/MainController.java
Labels: bug, documentation, 5.x

#337 [ENHANCEMENT] Add List for AbstractController
  code/core/src/controller/MainController.java
  code/core/test/controller/MainControllerTest.java
Labels: enhancement, 5.x

#344 Update gson version and add dependencies checker
  code/build.gradle
Labels: bug, enhancement, toolchain, 5.x

#342 Update gson version and add dependencies checker (version4)
  code/build.gradle
Labels: bug, enhancement, toolchain, 4.x
