Repository Programmiermethoden/PM-Dungeon, pull requests merged in 2022-02, with the labels that each got.

#163 Toolchain: build.gradle and test.yml modified
  .github/workflows/test.yml
  code/build.gradle
  code/checkstyle-config/checks.xml
  code/core/src/controller/MainController.java
  code/core/src/level/elements/Level.java
  code/core/src/level/elements/room/Room.java
  code/core/src/level/elements/room/Tile.java
  code/core/src/level/generator/LevelLoader/LevelLoader.java
  code/core/src/level/generator/dummy/DummyGenerator.java
  code/core/src/level/generator/dungeong/graphg/GraphG.java
  code/core/src/level/generator/dungeong/levelg/Chain.java
  code/core/src/level/generator/dungeong/levelg/ConfigurationSpace.java
  code/core/src/level/generator/dungeong/levelg/LevelG.java
  code/core/src/level/generator/dungeong/roomg/ReplacementLoader.java
  code/core/src/level/generator/dungeong/roomg/RoomTemplate.java
  code/core/src/level/generator/dungeong/roomg/RoomTemplateLoader.java
  code/core/src/textures/TextureHandler.java
  code/core/src/textures/TextureMap.java
  code/core/test/controller/EntityControllerTest.java
  code/core/test/controller/HUDControllerTest.java
  code/core/test/graphic/AnimationTest.java
  code/core/test/graphic/DungeonCameraTest.java
  code/core/test/graphic/HUDCameraTest.java
  code/core/test/graphic/PainterTest.java
  code/gradle.properties
Labels: toolchain

#171 Convert Point<->Coordinate
  code/core/src/level/tools/Coordinate.java
  code/core/src/tools/Point.java
Labels: enhancement

#131 Documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  documentation/aosp_format_de.md
  documentation/quickstart_de.md
  documentation/quickstart_en.md
Labels: documentation

#175 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#195 add smimple uml
  documentation/figs/simple_uml.png
  documentation/figs/simple_uml.uxf
  documentation/quickstart_de.md
Labels: documentation

#210 DungeonG: Feste Türen
  code/core/src/level/generator/dungeong/levelg/ConfigurationSpace.java
  code/core/src/level/generator/dungeong/levelg/LevelG.java
  code/core/src/level/generator/dungeong/roomg/ReplacementLoader.java
  code/core/src/level/generator/dungeong/roomg/RoomTemplate.java
  code/core/src/textures/TextureHandler.java
  code/core/test/controller/EntityControllerTest.java
  code/core/test/controller/HUDControllerTest.java
Labels: enhancement
